# Generated by Django 4.1.1 on 2022-09-25 16:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
