# Generated by Django 4.1.1 on 2022-09-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titleTag',
            field=models.CharField(default='Awesome Block', max_length=255),
        ),
    ]
