# Generated by Django 4.1.1 on 2022-09-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_post_titletag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titleTag',
            field=models.CharField(default='Awesome Blog', max_length=255),
        ),
    ]
