# Generated by Django 4.1.1 on 2022-09-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_post_titletag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titleTag',
            field=models.CharField(max_length=255),
        ),
    ]
